available_regions:
  -
    code: "test1"
    name: "Africa (Cape Town)"
    rir: "arin"
    too_close_codes: []
  -
    code: "test2"
    name: "Asia Pacific (Hong Kong)"
    rir: "apnic"
    too_close_codes: []